# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.6
  # aliased to a recent 7.x version

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source
#    - php -r "copy('.env.example', '.env');"
#    - php artisan key:generate

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: composer coverage

after_script:
  - composer codacy

